import {useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {BookOpen, Grid2X2, List, RotateCcw, Search} from 'lucide-react';
import useResource from '../../hooks/useResource';
import {CourseCard, Empty, Hero, Pagination, ResourceState, SupportBanner} from '../../components/common/PlatformUI';
export default function CoursesPage() {
  const resource = useResource('/courses'), [params,setParams] = useSearchParams();
  const query=params.get('q')||'',grade=params.get('grade')||'',subject=params.get('subject')||'',sort=params.get('sort')||'newest';
  const [list,setList]=useState(false);
  const courses=resource.data||[],grades=[...new Map(courses.filter(c=>c.grade).map(c=>[c.grade._id,c.grade])).values()],subjects=[...new Set(courses.map(c=>c.subject).filter(Boolean))];
  const filtered=courses.filter(c=>(!grade||c.grade?._id===grade)&&(!subject||c.subject===subject)&&`${c.title} ${c.description} ${c.subject}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'ar'):new Date(b.createdAt)-new Date(a.createdAt));
  const pages=Math.ceil(filtered.length/12),page=Math.max(1,Math.min(Number(params.get('page'))||1,pages||1));
  function update(key,value){const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);next.delete('page');setParams(next);}
  return <><Hero title="المحتوى التعليمي" subtitle="اكتشف عالمًا من المعرفة مع دوراتنا التعليمية المسجلة" compact><div className="hero-features"><span><BookOpen/>دروس منظمة</span><span>محتوى تعليمي متكامل</span><span>تعلم حسب وقتك</span></div></Hero><section className="site-container catalog-layout section"><div className="catalog-main"><div className="catalog-toolbar"><div><h2>جميع الدورات</h2><p>{filtered.length} دورة متاحة</p></div><div className="toolbar-options"><button aria-label="عرض شبكي" aria-pressed={!list} onClick={()=>setList(false)}><Grid2X2/></button><button aria-label="عرض قائمة" aria-pressed={list} onClick={()=>setList(true)}><List/></button><select aria-label="ترتيب الدورات" value={sort} onChange={e=>update('sort',e.target.value)}><option value="newest">الأحدث أولًا</option><option value="title">حسب الاسم</option></select></div></div><ResourceState resource={resource}>{filtered.length?<div className={`card-grid ${list?'list-view':''}`}>{filtered.slice((page-1)*12,page*12).map(c=><CourseCard key={c._id} course={c}/>)}</div>:<Empty>{courses.length?'لا توجد دورات تطابق البحث.':'لا توجد دورات منشورة بعد.'}</Empty>}</ResourceState><Pagination page={page} total={pages} onChange={n=>{const next=new URLSearchParams(params);next.set('page',n);setParams(next);}}/></div><aside className="site-panel filter-panel"><div className="input-wrap"><Search size={17}/><input aria-label="ابحث في الدورات" placeholder="ابحث في الدورات..." value={query} onChange={e=>update('q',e.target.value)}/></div><h3>الصف الدراسي</h3><button className={!grade?'filter-choice active':'filter-choice'} onClick={()=>update('grade','')}>الكل<span>{courses.length}</span></button>{grades.map(g=><button key={g._id} className={grade===g._id?'filter-choice active':'filter-choice'} onClick={()=>update('grade',g._id)}>{g.name}<span>{courses.filter(c=>c.grade?._id===g._id).length}</span></button>)}<h3>المواد التعليمية</h3><select aria-label="المادة التعليمية" value={subject} onChange={e=>update('subject',e.target.value)}><option value="">جميع المواد</option>{subjects.map(s=><option key={s}>{s}</option>)}</select><button className="site-button light full" onClick={()=>setParams({})}><RotateCcw size={16}/>إعادة تعيين الفلاتر</button></aside></section><SupportBanner/></>;
}
