import {useEffect,useState} from 'react';
import api from '../../services/api';
export default function LessonsManagementPage(){
 const [courses,setCourses]=useState([]),[modules,setModules]=useState([]),[lessons,setLessons]=useState([]),[title,setTitle]=useState(''),[courseId,setCourse]=useState(''),[moduleId,setModule]=useState(''),[kind,setKind]=useState('lesson'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const [c,m,l]=await Promise.all([api.get('/admin/courses'),api.get('/admin/modules'),api.get('/admin/lessons')]);setCourses(c.data.data);setModules(m.data.data);setLessons(l.data.data);}
 useEffect(()=>{let live=true;Promise.all([api.get('/admin/courses'),api.get('/admin/modules'),api.get('/admin/lessons')]).then(([c,m,l])=>{if(live){setCourses(c.data.data);setModules(m.data.data);setLessons(l.data.data);}}).catch(()=>{if(live)setMessage('تعذر تحميل البيانات');});return()=>{live=false;};},[]);
 async function action(url,data={},method='post'){setBusy(true);try{await api[method](url,data);await load();setMessage('تم الحفظ');}catch(e){setMessage(e.response?.data?.error?.message||'تعذر الحفظ');}finally{setBusy(false);}}
 return <main className="bg-white p-6 rounded text-text-primary space-y-5"><h1>الدروس والموديولات</h1><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();action(kind==='module'?'/admin/modules/CreateModule':'/admin/lessons',{title,courseId,...(kind==='lesson'&&moduleId?{moduleId}:{})});}}><select aria-label="النوع" value={kind} onChange={e=>setKind(e.target.value)}><option value="lesson">درس</option><option value="module">موديول</option></select><input aria-label="العنوان" required minLength={2} value={title} onChange={e=>setTitle(e.target.value)}/><select aria-label="الكورس" required value={courseId} onChange={e=>{setCourse(e.target.value);setModule('');}}><option value="">اختر الكورس</option>{courses.map(c=><option key={c._id} value={c._id}>{c.title}</option>)}</select>{kind==='lesson'&&<select aria-label="الموديول" value={moduleId} onChange={e=>setModule(e.target.value)}><option value="">بدون موديول</option>{modules.filter(m=>String(m.courseId?._id||m.courseId)===courseId).map(m=><option key={m._id} value={m._id}>{m.title}</option>)}</select>}<button disabled={busy}>إضافة</button></form><p role="status">{message}</p>{[['module',modules],['lesson',lessons]].map(([type,rows])=><section key={type}><h2>{type==='module'?'الموديولات':'الدروس'}</h2>{rows.map(row=><div className="border p-3 flex gap-3" key={row._id}><span>{row.title} ({row.status})</span><button disabled={busy} onClick={()=>action('/admin/'+(type==='module'?'modules':'lessons')+'/'+row._id+(row.status==='published'?'/hide':'/publish'),{},'patch')}>{row.status==='published'?'إخفاء':'نشر'}</button></div>)}</section>)}</main>;
}

