import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import api from '../../services/api';
export default function UploadVideoPage(){
 const navigate=useNavigate(),[lessons,setLessons]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({title:'',lessonId:'',videoUrl:'',thumbnailUrl:'',durationSeconds:0,accessLevel:'paid',status:'draft'});
 useEffect(()=>{api.get('/admin/lessons').then(r=>setLessons(r.data.data)).catch(e=>setError(e.response?.data?.error?.message||'تعذر تحميل الدروس'));},[]);
 async function submit(e){e.preventDefault();setBusy(true);try{await api.post('/admin/videos',{...form,durationSeconds:Number(form.durationSeconds)});navigate('/admin/video');}catch(e){setError(e.response?.data?.error?.message||'تعذر الحفظ');}finally{setBusy(false);}}
 return <main className="max-w-2xl bg-white p-6 rounded-2xl text-text-primary space-y-4"><h1>إضافة فيديو</h1><Link to="/admin/lessons">إدارة الدروس والموديولات</Link><form onSubmit={submit} className="grid gap-4"><label>عنوان الفيديو<input className="border p-2 block w-full" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>الدرس<select className="border p-2 block w-full" required value={form.lessonId} onChange={e=>setForm({...form,lessonId:e.target.value})}><option value="">اختر الدرس</option>{lessons.map(l=><option key={l._id} value={l._id}>{l.courseId?.title} — {l.title}</option>)}</select></label>{['videoUrl','thumbnailUrl','durationSeconds'].map(key=><label key={key}>{{videoUrl:'رابط الفيديو HTTPS',thumbnailUrl:'رابط صورة الفيديو',durationSeconds:'المدة بالثواني'}[key]}<input className="border p-2 block w-full" type={key==='durationSeconds'?'number':'url'} min="0" required={key==='videoUrl'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>الوصول<select value={form.accessLevel} onChange={e=>setForm({...form,accessLevel:e.target.value})}><option value="paid">للمشتركين</option><option value="free">معاينة مجانية</option></select></label><label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">مسودة</option><option value="published">منشور</option></select></label><button disabled={busy} className="bg-blue-600 text-white p-3 rounded">{busy?'جاري الحفظ…':'حفظ الفيديو'}</button><p role="alert">{error}</p></form></main>;
}

